# Generated by Django 4.2.7 on 2023-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowingmovie',
            name='image',
            field=models.URLField(default='https://user-images.githubusercontent.com/52632898/161646398-6d49eca9-267f-4eab-a5a7-6ba6069d21df.png'),
        ),
        migrations.AlterField(
            model_name='upcomingmovie',
            name='image',
            field=models.URLField(default='https://user-images.githubusercontent.com/52632898/161646398-6d49eca9-267f-4eab-a5a7-6ba6069d21df.png'),
        ),
    ]
